#判断是否载入该yaml文件
load_param_flag: 1

#判读是否有组名,0无组名，1有组名
group_flag: 0
# group_flag:0  启动  ns_flag:=g0  无组名
# group_flag:1  启动  ns_flag:=g1  有组名

model_name0: uav0

## 定位信息
# tof+T265定位
tof_usb: /dev/tof  # tof端口名
baud_tof_rate: 115200   # tof波特率
# 动捕定位
mocap_object: Tracker0 # 动捕刚体名
